@base_url= http://localhost:4510/
###

get {{base_url}}
###
get {{base_url}}api/parkings
###
get {{base_url}}api/parkings/664e09fce71633614b2fdb62
###
post {{base_url}}api/parkings
Content-Type: application/json

{
    "name": "Noord",
    "stad": "664e09492b7e121079a60cf7",
    "plaatsen": 750
}

###
put {{base_url}}api/parkings/664f5485b9d041425c7d3112
Content-Type: application/json

{
    "name": "Noord Parking",
    "stad": "664e09492b7e121079a60cf7",
    "plaatsen": 750
}


###
delete {{base_url}}api/parkings/664f5485b9d041425c7d3112


###
get {{base_url}}api/parkings/getAllParkingsByStad/664e090c2b7e121079a60cf3

###
get {{base_url}}api/steden

###
get {{base_url}}api/steden/664e097b2b7e121079a60cff

###
post {{base_url}}api/steden
Content-Type: application/json

{
    "name": "Ledegem",
    "postcode": 8065
}

###
put {{base_url}}api/steden/664f5637e5bf5d0522fc8aad
Content-Type: application/json

{
    "name": "Dublin",
    "postcode": 108765
}
###
delete {{base_url}}api/steden/664f5637e5bf5d0522fc8aad

###
get {{base_url}}api/registrations

###

get {{base_url}}api/registrations/getRegistrationByParkingId/664e09fce71633614b2fdb62

###
post {{base_url}}api/registrations
Content-Type: application/json

{
    "nummerplaat": "2-DKH-877",
    "parking": "664e09fce71633614b2fdb62"
}
###
put {{base_url}}api/registrations/664f58f1e5bf5d0522fc8ab8
Content-Type: application/json

{
    "nummerplaat": "2-DKF-877",
    "parking": "664e09fce71633614b2fdb62"
}

###
delete {{base_url}}api/registrations/664f58f1e5bf5d0522fc8ab8


###
post {{base_url}}api/users
Content-Type: application/json

{
    "email": "igorseynaeve@outlook.be",
    "name": "Igor Seynaeve 2",
    "password": "Azerty-123",
    "isAdmin": false
}

###
post {{base_url}}api/auth
Content-Type: application/json

{
    "email": "igorseynaeve@outlook.be",
    "password": "Azerty-123"
}

###
@auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjUxZGU4ZDkzM2I2N2MzZjlkN2QwMjQiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzE2NjQxNDg5LCJleHAiOjE3MTY2NDUwODl9.uzOIa8fPFyCqwyWggQNYtqz0QFuJ03haXjjk0G_tCwQ
get {{base_url}}api/users/me
x-auth-token: {{auth-token}}